// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware for Robots)
// Copyright (C) 1999-2005
// Department of Neuroinformatics, University of Ulm, Germany
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software Foundation,
// Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
// $Id$
//
#ifndef BAP_ArbiterParameters_h
#define BAP_ArbiterParameters_h

#include <iostream>
#include <map>

// forward declarations
class QDomNode;
class QDomElement;

namespace Miro
{
  namespace BAP
  {
    // forward declarations
    class Behaviour;
    class ActionPattern;
    class Arbiter;
    class ArbiterParameters;

    //! Output stream operator for debug purposes.
    std::ostream&
    operator << (std::ostream& ostr, const ArbiterParameters& _params);

    //! Base class for all parameter classes of derived Arbiters.
    /**
     * This class should actually be generated by a parameters XML file.
     * But we need some dirty tricks, that the clean design of
     * the parameters definitions does not allow...
     *
     * @author Hans Utz
     */
    struct ArbiterParameters
    {
      //------------------------------------------------------------------------
      // public types
      //------------------------------------------------------------------------

      //! Mapping of behaviour id's to the registration order.
      /**
       * The priority based arbiter chose the active behaviours 
       * actuatory request with the lowest registration number.
       */
      typedef std::map<Behaviour *, unsigned int> RegistrationMap;
      
      //------------------------------------------------------------------------
      // public methods
      //------------------------------------------------------------------------

      //! Map of the behaviours priorities.
      RegistrationMap priorities;
      
      //! Default constructor.
      ArbiterParameters();
      //! Copy constructor.
      ArbiterParameters(ArbiterParameters const&);
      //! Virtual destructor.
      virtual ~ArbiterParameters();
      
      //! XML-parsingoperator.
      virtual void operator <<= (const QDomNode&);
      //! XML-parsingoperator.
      virtual QDomElement operator >>= (QDomNode&) const;
      
      //! Register behaviours for acces control
      virtual void registerBehaviour(Behaviour * _behaviour);
      
    protected:
      //------------------------------------------------------------------------
      // protected methods
      //------------------------------------------------------------------------

      //! Dump the BehaviourParameters to the specified output stream.
      virtual void printToStream(std::ostream& ostr) const;
      
      //------------------------------------------------------------------------
      // protected data
      //------------------------------------------------------------------------

      //!  To assign for the next registered behaviour.
      unsigned int nextNumber_;
      
    private:
      //------------------------------------------------------------------------
      // hidden methods
      //------------------------------------------------------------------------
      //! Assignement operator.
      ArbiterParameters& operator=(ArbiterParameters const&);

      //------------------------------------------------------------------------
      // private data
      //------------------------------------------------------------------------

      //! Backlink to the action pattern the parameterized arbiter belongs to.
      ActionPattern * pattern;
      
      //------------------------------------------------------------------------
      // friend declarations
      //------------------------------------------------------------------------

      friend class Arbiter;
      friend class ActionPattern;
      friend std::ostream& operator << (std::ostream& ostr,
					const ArbiterParameters& _params);
    };
  }
}
#endif
