// -*- c++ -*- ///////////////////////////////////////////////////////////////
// This file was auto-generated by MakeParameters
//////////////////////////////////////////////////////////////////////////////
#ifndef Parameters_h_681312
#define Parameters_h_681312

#include "faulTty/Parameters.h"

#include <ace/INET_Addr.h>
#include <iostream>
#include <miro/Angle.h>
#include <miro/ScanDescriptionC.h>
#include <miro/Singleton.h>
#include <qdom.h>
#include <set>
#include <vector>

namespace FaulMotor
{
  class Parameters : public FaulTty::Parameters
  {
    typedef FaulTty::Parameters Super;

  public: 
    bool camera;
    bool cameraUpsideDown;
    Miro::ScanDescriptionIDL infraredDescription;
    bool infrared;
    Miro::DifferentialMotionParameters motion;
    Miro::ScanDescriptionIDL sonarDescription;
    Miro::ScanDescriptionIDL tactileDescription;
    bool tactile;
    bool sonar;

    static Miro::Singleton<Parameters> instance;

    Parameters();

    virtual void operator <<= (const QDomNode&);
    virtual QDomElement operator >>= (QDomNode&) const;
  protected:
    virtual void printToStream(std::ostream&) const;
  };
};

#endif // Parameters_h
