// -*- c++ -*- ///////////////////////////////////////////////////////////////
// This file was auto-generated by MakeParameters
//////////////////////////////////////////////////////////////////////////////
#ifndef Parameters_h_393887
#define Parameters_h_393887

#include "miro/Parameters.h"

#include <ace/INET_Addr.h>
#include <iostream>
#include <miro/Angle.h>
#include <miro/Singleton.h>
#include <qdom.h>
#include <set>
#include <vector>

namespace FaulMotor
{
  class Parameters : public Miro::ConfigParameters
  {
    typedef Miro::ConfigParameters Super;

  public: 
    Miro::DifferentialMotionParameters motion;
    double maxNegAccel;
    double maxPosAccel;
    double leftTicksPerMM;
    Miro::TtyParameters leftWheel;
    double rightTicksPerMM;
    Miro::TtyParameters rightWheel;
    double speedConvFactor;

    static Miro::Singleton<Parameters> instance;

    Parameters();

    virtual void operator <<= (const QDomNode&);
    virtual QDomElement operator >>= (QDomNode&) const;
  protected:
    virtual void printToStream(std::ostream&) const;
  };
};

#endif // Parameters_h
