## -*- Makefile -*- ##########################################################
##
## This file is part of Miro (The Middleware For Robots)
##
## (c) 1999, 2000,, 2001
## Department of Neural Information Processing, University of Ulm, Germany
##
## $Id$
## $Date$
## 
##
## Miro/src/miro/Makefile.MiroSvc
##
##############################################################################

## you can toggle the debug and optimize flags at this point
# debug = 1
# optimize = 0

## Only build static library 
static_libs_only = 1

## this is the name of the resulting library
NAME     = miroSvc

MAKEFILE = Makefile.MiroSvc
LIB      = lib$(NAME).a
SHLIB    = lib$(NAME).$(SOEXT)

PARAMS_SRC = Parameters.xml

## this I didn't understand yet
# VPATH=.:Naming
# ACE_SHLIBS = -lTAO

#----------------------------------------------------------------------------
#	Include macros
#----------------------------------------------------------------------------

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(MIRO_ROOT)/include/makeinclude/macros.miro.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

## specify your library files here
IDL_FILES =	Time \
		Exception \
		WorldPoint \
		Position \
		Velocity \
		MotionStatus \
		Odometry \
		Motion \
		ClosedMotion \
		SynchroMotion \
		DifferentialMotion \
		Stall \
		\
		ScanDescription \
		RangeEvent \
		RangeSensor \
		\
		Pan \
		Tilt \
		PanTilt \
		\
		Buttons \
		Video

ifneq (,$(findstring Deprecated,$(MIRO_COMPONENTS)))
  IDL_FILES += 	ImageDefinitions \
		Image
endif
ifneq (,$(findstring Pioneer1,$(MIRO_COMPONENTS)))
  IDL_FILES += 	PioneerStall \
		PioneerMotion
endif
ifneq (,$(findstring Sparrow99,$(MIRO_COMPONENTS)))
  ifeq (,$(findstring Pioneer1, $(MIRO_COMPONENTS)))
    IDL_FILES +=PioneerStall \
		PioneerMotion
  endif
  IDL_FILES +=	Kicker \
		SparrowPanTilt \
		SparrowStall \
		SparrowMotion
endif
ifneq (,$(findstring B21,$(MIRO_COMPONENTS)))
  IDL_FILES +=	Laser \
		DtlkSpeech \
		DirectedPerceptionPanTilt \
		B21Buttons \
		B21Motion
endif


IDL_SRC = \
        $(addsuffix S.cpp, $(IDL_FILES))

FILES =	\
	XmlParse \
	DevParameters \
	TtyParameters \
	DevConnection \
	DevEventHandler \
	DevConsumer \
	TtyConnection \
	RangeSensorImpl \
	OdometryImpl \
	MotionImpl \
	DifferentialMotionImpl \
	MotionParameters


DEFS  = $(addsuffix .h,$(FILES))
LSRC  =  $(IDL_SRC) $(addsuffix .cpp,$(FILES))

#----------------------------------------------------------------------------
#	Include targets
#----------------------------------------------------------------------------

default: all

include $(TAO_ROOT)/rules.tao.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.lib.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
include $(MIRO_ROOT)/include/makeinclude/rules.miro.GNU

#----------------------------------------------------------------------------
#       Local targets (and local hacks)
#----------------------------------------------------------------------------

# Extra dependencies not caught by make depend.

.PRECIOUS: $(foreach file, $(IDL_FILES), $(foreach ext, $(IDL_EXT), $(file)$(ext))))

realclean: clean
	-$(RM) $(foreach file, $(IDL_FILES), $(foreach ext, $(IDL_EXT), $(file)$(ext)))


# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


.obj/TimeS.o .obj/TimeS.o .obj/TimeS.o .obj/TimeS.o: TimeS.cpp TimeS.h TimeC.h TimeC.i.h TimeS.i.h

.obj/ExceptionS.o .obj/ExceptionS.o .obj/ExceptionS.o .obj/ExceptionS.o: ExceptionS.cpp ExceptionS.h ExceptionC.h ExceptionC.i.h \
 ExceptionS.i.h

.obj/WorldPointS.o .obj/WorldPointS.o .obj/WorldPointS.o .obj/WorldPointS.o: WorldPointS.cpp WorldPointS.h WorldPointC.h \
 WorldPointC.i.h WorldPointS.i.h

.obj/PositionS.o .obj/PositionS.o .obj/PositionS.o .obj/PositionS.o: PositionS.cpp PositionS.h WorldPointS.h WorldPointC.h \
 WorldPointC.i.h WorldPointS.i.h PositionC.h PositionC.i.h \
 PositionS.i.h

.obj/VelocityS.o .obj/VelocityS.o .obj/VelocityS.o .obj/VelocityS.o: VelocityS.cpp VelocityS.h VelocityC.h VelocityC.i.h \
 VelocityS.i.h

.obj/MotionStatusS.o .obj/MotionStatusS.o .obj/MotionStatusS.o .obj/MotionStatusS.o: MotionStatusS.cpp MotionStatusS.h TimeS.h TimeC.h \
 TimeC.i.h TimeS.i.h PositionS.h WorldPointS.h WorldPointC.h \
 WorldPointC.i.h WorldPointS.i.h PositionC.h PositionC.i.h \
 PositionS.i.h VelocityS.h VelocityC.h VelocityC.i.h VelocityS.i.h \
 MotionStatusC.h MotionStatusC.i.h MotionStatusS.i.h

.obj/OdometryS.o .obj/OdometryS.o .obj/OdometryS.o .obj/OdometryS.o: OdometryS.cpp OdometryS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h PositionS.h WorldPointS.h WorldPointC.h \
 WorldPointC.i.h WorldPointS.i.h PositionC.h PositionC.i.h \
 PositionS.i.h MotionStatusS.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h \
 VelocityS.h VelocityC.h VelocityC.i.h VelocityS.i.h MotionStatusC.h \
 MotionStatusC.i.h MotionStatusS.i.h OdometryC.h OdometryC.i.h \
 OdometryS.i.h

.obj/MotionS.o .obj/MotionS.o .obj/MotionS.o .obj/MotionS.o: MotionS.cpp MotionS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h VelocityS.h VelocityC.h VelocityC.i.h \
 VelocityS.i.h MotionC.h MotionC.i.h MotionS.i.h

.obj/ClosedMotionS.o .obj/ClosedMotionS.o .obj/ClosedMotionS.o .obj/ClosedMotionS.o: ClosedMotionS.cpp ClosedMotionS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h ClosedMotionC.h \
 ClosedMotionC.i.h ClosedMotionS.i.h

.obj/SynchroMotionS.o .obj/SynchroMotionS.o .obj/SynchroMotionS.o .obj/SynchroMotionS.o: SynchroMotionS.cpp SynchroMotionS.h MotionS.h \
 ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h VelocityS.h \
 VelocityC.h VelocityC.i.h VelocityS.i.h MotionC.h MotionC.i.h \
 MotionS.i.h SynchroMotionC.h SynchroMotionC.i.h SynchroMotionS.i.h

.obj/DifferentialMotionS.o .obj/DifferentialMotionS.o .obj/DifferentialMotionS.o .obj/DifferentialMotionS.o: DifferentialMotionS.cpp DifferentialMotionS.h \
 MotionS.h ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h \
 VelocityS.h VelocityC.h VelocityC.i.h VelocityS.i.h MotionC.h \
 MotionC.i.h MotionS.i.h DifferentialMotionC.h DifferentialMotionC.i.h \
 DifferentialMotionS.i.h

.obj/StallS.o .obj/StallS.o .obj/StallS.o .obj/StallS.o: StallS.cpp StallS.h StallC.h StallC.i.h StallS.i.h

.obj/ScanDescriptionS.o .obj/ScanDescriptionS.o .obj/ScanDescriptionS.o .obj/ScanDescriptionS.o: ScanDescriptionS.cpp ScanDescriptionS.h \
 ScanDescriptionC.h ScanDescriptionC.i.h ScanDescriptionS.i.h

.obj/RangeEventS.o .obj/RangeEventS.o .obj/RangeEventS.o .obj/RangeEventS.o: RangeEventS.cpp RangeEventS.h TimeS.h TimeC.h TimeC.i.h \
 TimeS.i.h RangeEventC.h RangeEventC.i.h RangeEventS.i.h

.obj/RangeSensorS.o .obj/RangeSensorS.o .obj/RangeSensorS.o .obj/RangeSensorS.o: RangeSensorS.cpp RangeSensorS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h ScanDescriptionS.h \
 ScanDescriptionC.h ScanDescriptionC.i.h ScanDescriptionS.i.h \
 RangeEventS.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h RangeEventC.h \
 RangeEventC.i.h RangeEventS.i.h RangeSensorC.h RangeSensorC.i.h \
 RangeSensorS.i.h

.obj/PanS.o .obj/PanS.o .obj/PanS.o .obj/PanS.o: PanS.cpp PanS.h ExceptionS.h ExceptionC.h ExceptionC.i.h \
 ExceptionS.i.h PanC.h PanC.i.h PanS.i.h

.obj/TiltS.o .obj/TiltS.o .obj/TiltS.o .obj/TiltS.o: TiltS.cpp TiltS.h ExceptionS.h ExceptionC.h ExceptionC.i.h \
 ExceptionS.i.h TiltC.h TiltC.i.h TiltS.i.h

.obj/PanTiltS.o .obj/PanTiltS.o .obj/PanTiltS.o .obj/PanTiltS.o: PanTiltS.cpp PanTiltS.h TiltS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h TiltC.h TiltC.i.h TiltS.i.h PanS.h \
 PanC.h PanC.i.h PanS.i.h PanTiltC.h PanTiltC.i.h PanTiltS.i.h

.obj/ButtonsS.o .obj/ButtonsS.o .obj/ButtonsS.o .obj/ButtonsS.o: ButtonsS.cpp ButtonsS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h \
 ButtonsC.h ButtonsC.i.h ButtonsS.i.h

.obj/VideoS.o .obj/VideoS.o .obj/VideoS.o .obj/VideoS.o: VideoS.cpp VideoS.h ExceptionS.h ExceptionC.h ExceptionC.i.h \
 ExceptionS.i.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h PositionS.h \
 WorldPointS.h WorldPointC.h WorldPointC.i.h WorldPointS.i.h \
 PositionC.h PositionC.i.h PositionS.i.h VideoC.h VideoC.i.h \
 VideoS.i.h

.obj/ImageDefinitionsS.o .obj/ImageDefinitionsS.o .obj/ImageDefinitionsS.o .obj/ImageDefinitionsS.o: ImageDefinitionsS.cpp ImageDefinitionsS.h \
 ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h TimeS.h \
 TimeC.h TimeC.i.h TimeS.i.h PositionS.h WorldPointS.h WorldPointC.h \
 WorldPointC.i.h WorldPointS.i.h PositionC.h PositionC.i.h \
 PositionS.i.h ImageDefinitionsC.h ImageDefinitionsC.i.h \
 ImageDefinitionsS.i.h

.obj/ImageS.o .obj/ImageS.o .obj/ImageS.o .obj/ImageS.o: ImageS.cpp ImageS.h ImageDefinitionsS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h TimeS.h TimeC.h TimeC.i.h \
 TimeS.i.h PositionS.h WorldPointS.h WorldPointC.h WorldPointC.i.h \
 WorldPointS.i.h PositionC.h PositionC.i.h PositionS.i.h \
 ImageDefinitionsC.h ImageDefinitionsC.i.h ImageDefinitionsS.i.h \
 ImageC.h ImageC.i.h ImageS.i.h

.obj/PioneerStallS.o .obj/PioneerStallS.o .obj/PioneerStallS.o .obj/PioneerStallS.o: PioneerStallS.cpp PioneerStallS.h StallS.h StallC.h \
 StallC.i.h StallS.i.h PioneerStallC.h PioneerStallC.i.h \
 PioneerStallS.i.h

.obj/PioneerMotionS.o .obj/PioneerMotionS.o .obj/PioneerMotionS.o .obj/PioneerMotionS.o: PioneerMotionS.cpp PioneerMotionS.h \
 DifferentialMotionS.h MotionS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h VelocityS.h VelocityC.h VelocityC.i.h \
 VelocityS.i.h MotionC.h MotionC.i.h MotionS.i.h DifferentialMotionC.h \
 DifferentialMotionC.i.h DifferentialMotionS.i.h ClosedMotionS.h \
 ClosedMotionC.h ClosedMotionC.i.h ClosedMotionS.i.h PioneerMotionC.h \
 PioneerMotionC.i.h PioneerMotionS.i.h

.obj/KickerS.o .obj/KickerS.o .obj/KickerS.o .obj/KickerS.o: KickerS.cpp KickerS.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h \
 ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h KickerC.h \
 KickerC.i.h KickerS.i.h

.obj/SparrowPanTiltS.o .obj/SparrowPanTiltS.o .obj/SparrowPanTiltS.o .obj/SparrowPanTiltS.o: SparrowPanTiltS.cpp SparrowPanTiltS.h PanS.h \
 ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h PanC.h \
 PanC.i.h PanS.i.h SparrowPanTiltC.h SparrowPanTiltC.i.h \
 SparrowPanTiltS.i.h

.obj/SparrowStallS.o .obj/SparrowStallS.o .obj/SparrowStallS.o .obj/SparrowStallS.o: SparrowStallS.cpp SparrowStallS.h StallS.h StallC.h \
 StallC.i.h StallS.i.h SparrowStallC.h SparrowStallC.i.h \
 SparrowStallS.i.h

.obj/SparrowMotionS.o .obj/SparrowMotionS.o .obj/SparrowMotionS.o .obj/SparrowMotionS.o: SparrowMotionS.cpp SparrowMotionS.h \
 DifferentialMotionS.h MotionS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h VelocityS.h VelocityC.h VelocityC.i.h \
 VelocityS.i.h MotionC.h MotionC.i.h MotionS.i.h DifferentialMotionC.h \
 DifferentialMotionC.i.h DifferentialMotionS.i.h SparrowMotionC.h \
 SparrowMotionC.i.h SparrowMotionS.i.h

.obj/LaserS.o .obj/LaserS.o .obj/LaserS.o .obj/LaserS.o: LaserS.cpp LaserS.h ExceptionS.h ExceptionC.h ExceptionC.i.h \
 ExceptionS.i.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h PositionS.h \
 WorldPointS.h WorldPointC.h WorldPointC.i.h WorldPointS.i.h \
 PositionC.h PositionC.i.h PositionS.i.h RangeSensorS.h \
 ScanDescriptionS.h ScanDescriptionC.h ScanDescriptionC.i.h \
 ScanDescriptionS.i.h RangeEventS.h RangeEventC.h RangeEventC.i.h \
 RangeEventS.i.h RangeSensorC.h RangeSensorC.i.h RangeSensorS.i.h \
 LaserC.h LaserC.i.h LaserS.i.h

.obj/DtlkSpeechS.o .obj/DtlkSpeechS.o .obj/DtlkSpeechS.o .obj/DtlkSpeechS.o: DtlkSpeechS.cpp DtlkSpeechS.h ExceptionS.h ExceptionC.h \
 ExceptionC.i.h ExceptionS.i.h DtlkSpeechC.h DtlkSpeechC.i.h \
 DtlkSpeechS.i.h

.obj/DirectedPerceptionPanTiltS.o .obj/DirectedPerceptionPanTiltS.o .obj/DirectedPerceptionPanTiltS.o .obj/DirectedPerceptionPanTiltS.o: DirectedPerceptionPanTiltS.cpp \
 DirectedPerceptionPanTiltS.h PanTiltS.h TiltS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h TiltC.h TiltC.i.h \
 TiltS.i.h PanS.h PanC.h PanC.i.h PanS.i.h PanTiltC.h PanTiltC.i.h \
 PanTiltS.i.h DirectedPerceptionPanTiltC.h \
 DirectedPerceptionPanTiltC.i.h DirectedPerceptionPanTiltS.i.h

.obj/B21ButtonsS.o .obj/B21ButtonsS.o .obj/B21ButtonsS.o .obj/B21ButtonsS.o: B21ButtonsS.cpp B21ButtonsS.h ButtonsS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h TimeS.h TimeC.h TimeC.i.h \
 TimeS.i.h ButtonsC.h ButtonsC.i.h ButtonsS.i.h B21ButtonsC.h \
 B21ButtonsC.i.h B21ButtonsS.i.h

.obj/B21MotionS.o .obj/B21MotionS.o .obj/B21MotionS.o .obj/B21MotionS.o: B21MotionS.cpp B21MotionS.h SynchroMotionS.h MotionS.h \
 ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h VelocityS.h \
 VelocityC.h VelocityC.i.h VelocityS.i.h MotionC.h MotionC.i.h \
 MotionS.i.h SynchroMotionC.h SynchroMotionC.i.h SynchroMotionS.i.h \
 ClosedMotionS.h ClosedMotionC.h ClosedMotionC.i.h ClosedMotionS.i.h \
 OdometryS.h PositionS.h WorldPointS.h WorldPointC.h WorldPointC.i.h \
 WorldPointS.i.h PositionC.h PositionC.i.h PositionS.i.h \
 MotionStatusS.h TimeS.h TimeC.h TimeC.i.h TimeS.i.h MotionStatusC.h \
 MotionStatusC.i.h MotionStatusS.i.h OdometryC.h OdometryC.i.h \
 OdometryS.i.h B21MotionC.h B21MotionC.i.h B21MotionS.i.h

.obj/XmlParse.o .obj/XmlParse.o .obj/XmlParse.o .obj/XmlParse.o: XmlParse.cpp XmlParse.h ScanDescriptionC.h \
 ScanDescriptionC.i.h

.obj/DevParameters.o .obj/DevParameters.o .obj/DevParameters.o .obj/DevParameters.o: DevParameters.cpp DevParameters.h Parameters.h

.obj/TtyParameters.o .obj/TtyParameters.o .obj/TtyParameters.o .obj/TtyParameters.o: TtyParameters.cpp TtyParameters.h DevParameters.h \
 Parameters.h

.obj/DevConnection.o .obj/DevConnection.o .obj/DevConnection.o .obj/DevConnection.o: DevConnection.cpp \
 \
 \
 \
 \


.obj/DevEventHandler.o .obj/DevEventHandler.o .obj/DevEventHandler.o .obj/DevEventHandler.o: DevEventHandler.cpp \
 \
 \
 \


.obj/DevConsumer.o .obj/DevConsumer.o .obj/DevConsumer.o .obj/DevConsumer.o: DevConsumer.cpp \
 \
 \


.obj/TtyConnection.o .obj/TtyConnection.o .obj/TtyConnection.o .obj/TtyConnection.o: TtyConnection.cpp \
 \
 \
 \
 \
 \


.obj/RangeSensorImpl.o .obj/RangeSensorImpl.o .obj/RangeSensorImpl.o .obj/RangeSensorImpl.o: RangeSensorImpl.cpp RangeSensorImpl.h \
 RangeSensorS.h ExceptionS.h ExceptionC.h ExceptionC.i.h \
 ExceptionS.i.h ScanDescriptionS.h ScanDescriptionC.h \
 ScanDescriptionC.i.h ScanDescriptionS.i.h RangeEventS.h TimeS.h \
 TimeC.h TimeC.i.h TimeS.i.h RangeEventC.h RangeEventC.i.h \
 RangeEventS.i.h RangeSensorC.h RangeSensorC.i.h RangeSensorS.i.h \
 Synch.h Exception.h StructuredPushSupplier.h

.obj/OdometryImpl.o .obj/OdometryImpl.o .obj/OdometryImpl.o .obj/OdometryImpl.o: OdometryImpl.cpp OdometryImpl.h OdometryS.h \
 ExceptionS.h ExceptionC.h ExceptionC.i.h ExceptionS.i.h PositionS.h \
 WorldPointS.h WorldPointC.h WorldPointC.i.h WorldPointS.i.h \
 PositionC.h PositionC.i.h PositionS.i.h MotionStatusS.h TimeS.h \
 TimeC.h TimeC.i.h TimeS.i.h VelocityS.h VelocityC.h VelocityC.i.h \
 VelocityS.i.h MotionStatusC.h MotionStatusC.i.h MotionStatusS.i.h \
 OdometryC.h OdometryC.i.h OdometryS.i.h Synch.h TimeHelper.h \
 StructuredPushSupplier.h

.obj/MotionImpl.o .obj/MotionImpl.o .obj/MotionImpl.o .obj/MotionImpl.o: MotionImpl.cpp MotionImpl.h MotionS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h VelocityS.h VelocityC.h \
 VelocityC.i.h VelocityS.i.h MotionC.h MotionC.i.h MotionS.i.h \
 MotionParameters.h Parameters.h Synch.h

.obj/DifferentialMotionImpl.o .obj/DifferentialMotionImpl.o .obj/DifferentialMotionImpl.o .obj/DifferentialMotionImpl.o: DifferentialMotionImpl.cpp \
 DifferentialMotionImpl.h DifferentialMotionS.h MotionS.h ExceptionS.h \
 ExceptionC.h ExceptionC.i.h ExceptionS.i.h VelocityS.h VelocityC.h \
 VelocityC.i.h VelocityS.i.h MotionC.h MotionC.i.h MotionS.i.h \
 DifferentialMotionC.h DifferentialMotionC.i.h DifferentialMotionS.i.h \
 MotionImpl.h MotionParameters.h Parameters.h Synch.h

.obj/MotionParameters.o .obj/MotionParameters.o .obj/MotionParameters.o .obj/MotionParameters.o: MotionParameters.cpp MotionParameters.h \
 Parameters.h

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
