// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 2005
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////

#ifndef InclinometerEvent_idl
#define InclinometerEvent_idl

#include "Time.idl"
#include "Inclination.idl"

module Miro
{
  //! Inclinometer reading notification
  /**
   * Used by the inclinometer implementation to send out an update
   * whenever new data is available.
   */
  struct InclinometerEventIDL
  {
    //! Timestamp of inclinometer reading
    TimeIDL time;
    //! New inclination (pitch and roll) angles, specified in radiants
    InclinationIDL inclination;
  };
};

#endif // InclinometerEvent_idl
