// -*- c++ -*- ///////////////////////////////////////////////////////////////
// This file was auto-generated by MakeParameters
//////////////////////////////////////////////////////////////////////////////
#ifndef Parameters_h_98016
#define Parameters_h_98016

#include "miro/Parameters.h"

#include <iostream>
#include <miro/Angle.h>
#include <qdom.h>
#include <set>
#include <vector>

namespace FaulTty
{
  class Parameters : public Miro::TtyParameters
  {
    typedef Miro::TtyParameters Super;

  public: 
    double angleConvFactor;
    double diffConvFactor;
    double distConvFactor;
    double rangeConvFactor;
    double vel2Divisor;
    double velConvFactor;

    Parameters();

    virtual void operator <<= (const QDomNode&);
    virtual QDomElement operator >>= (QDomNode&) const;
  protected:
    virtual void printToStream(std::ostream&) const;
  };
};

#endif // Parameters_h
