// -*- c++ -*- ///////////////////////////////////////////////////////////////
// This file was auto-generated by MakeParameters
//////////////////////////////////////////////////////////////////////////////
#ifndef Parameters_h_170115
#define Parameters_h_170115

#include "botsvcs/BAP/Parameters.h"

#include <iostream>
#include <qdom.h>

class DummyBehaviourParameters : public Miro::BAP::TimedBehaviourParameters
{
  typedef Miro::BAP::TimedBehaviourParameters Super;

public: 
  int sendTransition;
  int dummy;

  DummyBehaviourParameters();

  virtual void operator <<= (const QDomNode&);
  virtual QDomElement operator >>= (QDomNode&) const;
protected:
  virtual void printToStream(std::ostream&) const;
};

class DummyBehaviourBParameters : public Miro::BAP::TimedBehaviourParameters
{
  typedef Miro::BAP::TimedBehaviourParameters Super;

public: 
  DummyBehaviourBParameters();

};

class DummyBehaviourDParameters : public Miro::BAP::TimedBehaviourParameters
{
  typedef Miro::BAP::TimedBehaviourParameters Super;

public: 
  DummyBehaviourDParameters();

};






class DummyArbiterParameters : public Miro::BAP::PriorityArbiterParameters
{
  typedef Miro::BAP::PriorityArbiterParameters Super;

public: 
  DummyArbiterParameters();

};



#endif // Parameters_h
