// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 2002
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
// BatteryEvent to broadcast informations about the battery status
//
//////////////////////////////////////////////////////////////////////////////
#ifndef BatteryEvent_idl
#define BatteryEvent_idl

#include "Exception.idl"

module Miro
{
  //! Battery montoring event.
  /** 
   *
   * BatteryEvent to broadcast informations about the battery status.
   *
   * @author Gerald Steinbauer
   */
  struct BatteryEventIDL
  {
    //! The current battery voltage (in volt).
    double voltage;

    //! Warnflag for low battery.
    boolean battery_low;

  };
};
#endif // BatteryEvent_idl
