// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 1999, 2000, 2001, 2002
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////
#ifndef CanonPanTilt_idl
#define CanonPanTilt_idl

#include "PanTilt.idl"

module Miro
{
  //! Struct representing a pantilt speed and acceleration configuration.
  struct CanonPanTiltSpdAccIDL
  {
    //! Target pan speed value in rad/s.
    double     targetpanspeed;
    //! Target tilt speed value in rad/s.
    double     targettiltspeed;
    //! Minimum pan speed value in rad/s.
    double     panminspeed;
    //! Maximum pan speed value in rad/s.
    double     panmaxspeed;
    //! Minimum tilt speed value in rad/s.
    double     tiltminspeed;
    //! Maximum tilt speed value in rad/s.
    double     tiltmaxspeed;
  };

  //! Struct representing a pantilt limits  configuration.
  struct CanonPanTiltLimitsIDL
  {
    //! Minimal pan position.
    double minpanposition;
    //! Maximal pan position.
    double maxpanposition;
    //! Minimal tilt position.
    double mintiltposition;
    //! Maximal tilt position.
    double maxtiltposition;
  };


  //! Interface to the panTilt unit supplied with canon VC series cameras.
  /**
   * This pantilt unit is mounted on the PeopleBot robot.  It registers as
   * "PanTilt" at the naming service in the specified naming context.
   * 
   * @author Guillem Pages Gassull
   */
  interface CanonPanTilt : Miro::PanTilt
  {
    //! Wait for the PTU to complete previous movement
    void waitCompletion() raises(Miro::EDevIO, Miro::ETimeOut);

    //! Move the PTU to the specified destination.
    /** The call awaits completion of the movement.
     */
    void setWaitPosition( in Miro::PanTiltPositionIDL dest) 
      raises(Miro::EOutOfBounds, Miro::EDevIO, Miro::ETimeOut);

    //! Set the actual speed and acceleration settings.
    void setSpdAcc( in CanonPanTiltSpdAccIDL dest )
      raises(Miro::EDevIO, Miro::ETimeOut, Miro::EOutOfBounds);

    //! Query the current speed and acceleration setting.
    /**
     * @return The actual speed and acceleration settings of the PTU.
     */
    CanonPanTiltSpdAccIDL  getSpdAcc() raises(Miro::EDevIO, Miro::ETimeOut);

    //! Query the limits of the PTU.
    /**
     * @return The actual limits settings of the PTU.
     */
    CanonPanTiltLimitsIDL  getLimits() raises(Miro::EDevIO, Miro::ETimeOut);

  };
};

#endif // CanonPanTilt_idl
