// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 2002
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////
#ifndef Charger_idl
#define Charger_idl

#include "Exception.idl"
#include "Battery.idl"

module Miro
{
  //! Interface for the Pioneer Charging module.
  /** 
   * Allows to use the Charging Module for the Pioneer 3DX Robot
   *
   * @author Gerald Steinbauer
   */
  interface Charger : Battery
  {
    //! deploy the charger
    void deployCharger() raises (EDevIO);

    //!  retract the charger
    void retractCharger() raises (EDevIO);

    //! get the status of the charger
    unsigned short getChargerStatus() raises (EDevIO);
  };
};
#endif // Charger_idl
