// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 2005
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////

#ifndef Inclination_idl
#define Inclination_idl

module Miro
{
  //! Structure for storing an inclination angle pair (pitch and roll)
  struct InclinationIDL
  {
    //! Pitch angle in radiants
    /**
     * Positive values indicate the robot facing an upward slope.
     */
    float pitch;
    //! Roll angle in radiants
    /**
     * Positive values indicate the robot being rolled to the left
     * from its own perspective.
     */
    float roll;
  };
};

#endif // Inclination_idl
