// -*- idl -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware for Robots)
// Copyright (C) 1999-2005
// Department of Neuroinformatics, University of Ulm, Germany
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software Foundation,
// Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
// $Id$
//
#ifndef Inclination_idl
#define Inclination_idl

module Miro
{
  //! Structure for storing an inclination angle pair (pitch and roll)
  struct InclinationIDL
  {
    //! Pitch angle in radiants
    /**
     * Positive values indicate the robot facing an upward slope.
     */
    float pitch;
    //! Roll angle in radiants
    /**
     * Positive values indicate the robot being rolled to the left
     * from its own perspective.
     */
    float roll;
  };
};

#endif // Inclination_idl
