// -*- idl -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware for Robots)
// Copyright (C) 1999-2005
// Department of Neuroinformatics, University of Ulm, Germany
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software Foundation,
// Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
// $Id$
//
#ifndef SparrowPanTilt_idl
#define SparrowPanTilt_idl

#include "Pan.idl"
#include "Time.idl"

module Miro
{
  struct PanEventIDL
  {
    TimeIDL time;
    double newAngle;
  };

  //! The specialized pan position specification of the Sparrow99 pan unit.
  struct PanPositionIDL
  {
    //! Panning angle in rad.
    double angle;
    //! The accuracy of the angle in rad.
    /**
     * The Sparrow99 pan can't tell, if the last setPan command is
     * already completed. Therefore this value is derived from the
     * last time setPan was called.
     *
     * (angle +/- accuracy) therefor is the range within which
     * the actual panning angle resides.
     */
    double accuracy;
  };

  //! Specialized interface for the Sparrows99 pan unit.
  /**
   * Yes, the name is misleading. The Sparrow99 once had a pantilt unit. But
   * it was downgraded to a simple pan unit...
   *
   * @author Hans Utz
   */
  interface SparrowPanTilt : Pan
  {
    //! Is the pan unit still in motion?
    boolean panning(in Miro::TimeIDL stamp);

    //! Get pan position and accuracy.
    PanPositionIDL currentPan(in Miro::TimeIDL stamp);
    
    void setPanSpeed(in float value) raises(EDevIO, EOutOfBounds);
  };
};

#endif // SparrowPanTilt_idl




