// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 2005
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////

#ifndef TCM2Event_idl
#define TCM2Event_idl

#include "Time.idl"
#include "Inclination.idl"
#include "FieldStrength.idl"

module Miro
{
  //! TCM2 reading notification
  /**
   * Used by the TCM2 module implementation to send out an update
   * whenever new data is available. This notification contains new
   * readings from all the TCM2's sensors: compass, inclinometer,
   * magnetometer and thermometer.   
   */
  struct TCM2EventIDL
  {
    //! Timestamp of reading
    TimeIDL time;
    //! New compass heading (in radiants relative to magnetic north)
    float heading;
    //! New inclination (pitch and roll) angle pair
    InclinationIDL inclination;
    //! New magnetic field strength (in uT)
    FieldStrengthIDL fieldstrength;
    //! New temperature (in degrees C)
    float temperature;
  };
};

#endif // TCM2Event_idl
