// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 2000, 2001, 2002
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////
#ifndef Tilt_idl
#define Tilt_idl

#include "Exception.idl"

module Miro
{
  //! Struct representing a tilting limits  configuration.
  struct TiltLimitsIDL
  {
    //! Minimal tilt position.
    double mintiltposition;
    //! Maximal tilt position.
    double maxtiltposition;
  };


  //! Basic interface for a tilting unit.
  /** 
   * @author Hans Utz
   */
  interface Tilt 
  {
    //! Set the tilting angle.
    /**
     * @param angle is specified in radiant.
     * @throw EOutOfBounds is thrown
     * if the specified tilitng angle is beyond the range of the tilting unit.
     * @throw EDevIO
     * is thrown to indicate low level device problems.
     */
    void setTilt(in double value) raises(EDevIO, EOutOfBounds);
    //! Get the current tilting angle.
    /**
     * @return The tilting angle, specified in radiant.
     * @throw EDevIO
     * is thrown to indicate low level device problems.
     */
    double getTilt() raises(EDevIO);

    //! Get the tilting angle limits.
    /**
     * @return The angles within the tilt unit works, specified in radiant.
     * @throw EDevIO
     * is thrown to indicate low level device problems.
     */
    TiltLimitsIDL getTiltLimits() raises(EDevIO);

  };
};

#endif // Tilt_idl
