// -*- c++ -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// (c) 1999, 2000, 2001, 2002
// Department of Neural Information Processing, University of Ulm, Germany
//
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////
#ifndef Velocity_idl
#define Velocity_idl

module Miro
{
  //! Struct holding a translational and rotational velocity.
  struct VelocityIDL
  {
    //!Translational velocity in mm/s.
    long translation;
    //! Rotational velocity in rad/s.
    double rotation;
  };
};

#endif // Velcity_idl




