// -*- c++ -*- ///////////////////////////////////////////////////////////////
// This file was auto-generated by MakeParameters
//////////////////////////////////////////////////////////////////////////////
#ifndef Parameters_h_952534
#define Parameters_h_952534

#include "miro/SvcParameters.h"

#include <ace/INET_Addr.h>
#include <ace/Time_Value.h>
#include <iostream>
#include <miro/Singleton.h>
#include <qdom.h>
#include <string>

namespace Inertial
{
  struct InertialParameters;
  std::ostream&
  operator << (std::ostream& ostr, const InertialParameters& rhs);

  class InertialParameters
  {
  public: 
    std::string device;
    std::string outputmode;
    std::string outputsettings;
    ACE_Time_Value pollInterval;
    Miro::InclinometerParameters inclinometer;

    static Miro::Singleton<InertialParameters> instance;

    InertialParameters();
    virtual ~InertialParameters();
    virtual char const * fullTypeName() const throw();

    virtual void operator <<= (const QDomNode&);
    virtual QDomElement operator >>= (QDomNode&) const;
  protected:
    virtual void printToStream(std::ostream&) const;
    friend
    std::ostream&
    operator << (std::ostream& ostr, const InertialParameters& rhs);
  };
}

#endif // Parameters_h
