// -*- c++ -*- ///////////////////////////////////////////////////////////////
// This file was auto-generated by MakeParameters
//////////////////////////////////////////////////////////////////////////////
#ifndef Parameters_h_851801
#define Parameters_h_851801

#include "miro/SvcParameters.h"

#include <ace/INET_Addr.h>
#include <ace/Time_Value.h>
#include <idl/ScanDescriptionC.h>
#include <iostream>
#include <miro/Singleton.h>
#include <qdom.h>
#include <string>

namespace Laser
{
  class Parameters : public Miro::TtyParameters
  {
    typedef Miro::TtyParameters Super;

  public: 
    bool stdCrystal;
    ACE_Time_Value pollInterval;
    bool continousMode;
    bool notify;
    bool positionStamps;
    bool statistics;
    int fov;
    double scanResolution;
    Miro::ScanDescriptionIDL laserDescription;

    static Miro::Singleton<Parameters> instance;

    Parameters();
    virtual char const * fullTypeName() const throw();

    virtual void operator <<= (const QDomNode&);
    virtual QDomElement operator >>= (QDomNode&) const;
  protected:
    virtual void printToStream(std::ostream&) const;
  };
}

#endif // Parameters_h
