#! bash

# various test runs for the performance evaluation of
# the logging client 


./LogPerformance -f OctetStream1K.log -p OctetStream1K -v -MiroNoNaming >2 OctetStream1K.cerr
./LogPerformance -f OctetStream100K.log -p OctetStream100K -v -MiroNoNaming >2 OctetStream100K.cerr
./LogPerformance -f MotionStatus.log -p MotionStatus -v -MiroNoNaming >2 MotionStatus.cerr
./LogPerformance -f RangeEvent.log -p RangeEvent -v -MiroNoNaming >2 RangeEvent.cerr
