## -*- Makefile -*- ##########################################################
##
## This file is part of Miro (The Middleware For Robots)
##
## (c) 2003
## Department of Neural Information Processing, University of Ulm, Germany
##
## $Id$
##
## Miro/src/video/Makefile.lib
##
##############################################################################

#----------------------------------------------------------------------------
#	Include macros
#----------------------------------------------------------------------------

# Only build static library 
static_libs_only = 1

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(MIRO_ROOT)/include/makeinclude/macros.miro.GNU

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

## this is the name of the resulting library
NAME     = miroVideo

MAKEFILE = Makefile.lib
LIB      = lib$(NAME).a
SHLIB    = lib$(NAME).$(SOEXT)


## this I didn't understand yet
# VPATH=.:Naming
# ACE_SHLIBS = -lTAO_Svc_Utils -lTAO -lACE

## specify your library files here
FILES =  \
	Parameters \
	BufferManager \
	BufferManager1394 \
	BufferManagerBTTV \
	BufferManagerMeteor \
	VideoFilter \
	VideoFilterBasic \
	VideoFilterRepository \
	VideoDevice \
	VideoAVDevice \
	VideoDeviceDummy \
	VideoConsumer \
	VideoImpl \
	VideoBrokerImpl \
	VideoServer 

ifneq (,$(findstring BTTV,$(MIRO_VIDEO_COMPONENTS)))
  FILES += \
	VideoDeviceBTTV
endif

ifneq (,$(findstring Meteor,$(MIRO_VIDEO_COMPONENTS)))
  FILES += \
	VideoDeviceMeteor
endif

ifneq (,$(findstring 1394,$(MIRO_VIDEO_COMPONENTS)))
  FILES += \
	VideoDevice1394 \
	VideoFilterYUVbase \
	VideoFilterYUV411toRGB \
	VideoFilterYUV411toYUV \
	VideoFilterYUV422toRGB \
	VideoFilterYUV422toYUV
endif

DEFS  = $(addsuffix .h,$(FILES))
LSRC  = $(addsuffix .cpp,$(FILES))

#----------------------------------------------------------------------------
#	Include targets
#----------------------------------------------------------------------------

## you can toggle the debug and optimize flags at this point
# debug = 1
# optimize = 0

include $(TAO_ROOT)/rules.tao.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.lib.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
include $(MIRO_ROOT)/include/makeinclude/rules.miro.GNU

#----------------------------------------------------------------------------
#       Local targets (and local hacks)
#----------------------------------------------------------------------------

.PRECIOUS: Parameters.cpp Parameters.h

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


.obj/Parameters.o .obj/Parameters.o .obj/Parameters.o .obj/Parameters.o: Parameters.cpp Parameters.h \
 \
 \


.obj/BufferManager.o .obj/BufferManager.o .obj/BufferManager.o .obj/BufferManager.o: BufferManager.cpp BufferManager.h \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i

.obj/BufferManager1394.o .obj/BufferManager1394.o .obj/BufferManager1394.o .obj/BufferManager1394.o: BufferManager1394.cpp BufferManager1394.h \
 BufferManager.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i

.obj/BufferManagerBTTV.o .obj/BufferManagerBTTV.o .obj/BufferManagerBTTV.o .obj/BufferManagerBTTV.o: BufferManagerBTTV.cpp BufferManagerBTTV.h \
 BufferManager.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i

.obj/BufferManagerMeteor.o .obj/BufferManagerMeteor.o .obj/BufferManagerMeteor.o .obj/BufferManagerMeteor.o: BufferManagerMeteor.cpp BufferManagerMeteor.h \
 BufferManager.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i ioctl_meteor.h

.obj/VideoFilter.o .obj/VideoFilter.o .obj/VideoFilter.o .obj/VideoFilter.o: VideoFilter.cpp VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i VideoImpl.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionS.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeS.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointS.i \
 /home/hutz/work/Miro.video/src/miro/PositionS.i \
 /home/hutz/work/Miro.video/src/miro/VideoS.i BufferManager.h \
 \
 \
 \


.obj/VideoFilterBasic.o .obj/VideoFilterBasic.o .obj/VideoFilterBasic.o .obj/VideoFilterBasic.o: VideoFilterBasic.cpp VideoFilterBasic.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \
 \


.obj/VideoFilterRepository.o .obj/VideoFilterRepository.o .obj/VideoFilterRepository.o .obj/VideoFilterRepository.o: VideoFilterRepository.cpp \
 VideoFilterRepository.h VideoFilterFactory.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \
 \
 VideoFilter.h \
 Parameters.h \
 \
 \
 VideoFilterLink.h

.obj/VideoDevice.o .obj/VideoDevice.o .obj/VideoDevice.o .obj/VideoDevice.o: VideoDevice.cpp VideoDevice.h VideoFilter.h \
 Parameters.h \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \


.obj/VideoAVDevice.o .obj/VideoAVDevice.o .obj/VideoAVDevice.o .obj/VideoAVDevice.o: VideoAVDevice.cpp VideoAVDevice.h VideoDevice.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \


.obj/VideoDeviceDummy.o .obj/VideoDeviceDummy.o .obj/VideoDeviceDummy.o .obj/VideoDeviceDummy.o: VideoDeviceDummy.cpp VideoDeviceDummy.h \
 VideoDevice.h VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 BufferManager.h \
 \
 \


.obj/VideoConsumer.o .obj/VideoConsumer.o .obj/VideoConsumer.o .obj/VideoConsumer.o: VideoConsumer.cpp VideoConsumer.h \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i VideoDevice.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i VideoImpl.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionS.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeS.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointS.i \
 /home/hutz/work/Miro.video/src/miro/PositionS.i \
 /home/hutz/work/Miro.video/src/miro/VideoS.i \
 \


.obj/VideoImpl.o .obj/VideoImpl.o .obj/VideoImpl.o .obj/VideoImpl.o: VideoImpl.cpp \
 \
 \
 \
 \
 \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i VideoImpl.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionS.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeS.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointS.i \
 /home/hutz/work/Miro.video/src/miro/PositionS.i \
 /home/hutz/work/Miro.video/src/miro/VideoS.i VideoFilter.h \
 Parameters.h VideoFilterLink.h \
 VideoConsumer.h \
 BufferManager.h

.obj/VideoBrokerImpl.o .obj/VideoBrokerImpl.o .obj/VideoBrokerImpl.o .obj/VideoBrokerImpl.o: VideoBrokerImpl.cpp VideoBrokerImpl.h \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 /home/hutz/work/Miro.video/src/miro/ExceptionS.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 /home/hutz/work/Miro.video/src/miro/TimeS.i \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/WorldPointS.i \
 \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/PositionS.i \
 \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 /home/hutz/work/Miro.video/src/miro/VideoS.i VideoFilter.h \
 Parameters.h \
 \
 \
 VideoFilterLink.h \


.obj/VideoServer.o .obj/VideoServer.o .obj/VideoServer.o .obj/VideoServer.o: VideoServer.cpp VideoServer.h VideoImpl.h \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 /home/hutz/work/Miro.video/src/miro/ExceptionS.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 /home/hutz/work/Miro.video/src/miro/TimeS.i \
 \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/WorldPointS.i \
 \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/PositionS.i \
 \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 /home/hutz/work/Miro.video/src/miro/VideoS.i \
 VideoDevice.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 VideoConsumer.h \
 VideoBrokerImpl.h VideoFilterRepository.h VideoFilterFactory.h \
 \
 \
 \
 \


.obj/VideoDeviceBTTV.o .obj/VideoDeviceBTTV.o .obj/VideoDeviceBTTV.o .obj/VideoDeviceBTTV.o: VideoDeviceBTTV.cpp VideoDeviceBTTV.h \
 VideoAVDevice.h VideoDevice.h VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 BufferManagerBTTV.h \
 BufferManager.h

.obj/VideoDeviceMeteor.o .obj/VideoDeviceMeteor.o .obj/VideoDeviceMeteor.o .obj/VideoDeviceMeteor.o: VideoDeviceMeteor.cpp VideoDeviceMeteor.h \
 ioctl_meteor.h VideoAVDevice.h VideoDevice.h VideoFilter.h \
 Parameters.h \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 BufferManagerMeteor.h \
 BufferManager.h \


.obj/VideoDevice1394.o .obj/VideoDevice1394.o .obj/VideoDevice1394.o .obj/VideoDevice1394.o: VideoDevice1394.cpp VideoDevice1394.h VideoDevice.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 BufferManager1394.h \
 BufferManager.h

.obj/VideoFilterYUVbase.o .obj/VideoFilterYUVbase.o .obj/VideoFilterYUVbase.o .obj/VideoFilterYUVbase.o: VideoFilterYUVbase.cpp VideoFilterYUVbase.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i

.obj/VideoFilterYUV411toRGB.o .obj/VideoFilterYUV411toRGB.o .obj/VideoFilterYUV411toRGB.o .obj/VideoFilterYUV411toRGB.o: VideoFilterYUV411toRGB.cpp \
 VideoFilterYUV411toRGB.h VideoFilterYUVbase.h VideoFilter.h \
 Parameters.h \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \
 \


.obj/VideoFilterYUV411toYUV.o .obj/VideoFilterYUV411toYUV.o .obj/VideoFilterYUV411toYUV.o .obj/VideoFilterYUV411toYUV.o: VideoFilterYUV411toYUV.cpp \
 VideoFilterYUV411toYUV.h VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \
 \


.obj/VideoFilterYUV422toRGB.o .obj/VideoFilterYUV422toRGB.o .obj/VideoFilterYUV422toRGB.o .obj/VideoFilterYUV422toRGB.o: VideoFilterYUV422toRGB.cpp \
 VideoFilterYUV422toRGB.h VideoFilterYUVbase.h VideoFilter.h \
 Parameters.h \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \


.obj/VideoFilterYUV422toYUV.o .obj/VideoFilterYUV422toYUV.o .obj/VideoFilterYUV422toYUV.o .obj/VideoFilterYUV422toYUV.o: VideoFilterYUV422toYUV.cpp \
 VideoFilterYUV422toYUV.h VideoFilter.h Parameters.h \
 \
 \
 \
 VideoFilterLink.h \
 \
 \
 /home/hutz/work/Miro.video/src/miro/ExceptionC.i \
 \
 /home/hutz/work/Miro.video/src/miro/TimeC.i \
 \
 \
 /home/hutz/work/Miro.video/src/miro/WorldPointC.i \
 /home/hutz/work/Miro.video/src/miro/PositionC.i \
 /home/hutz/work/Miro.video/src/miro/VideoC.i \
 \


# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
