## -*- Makefile -*- ##########################################################
##
## This file is part of Miro (The Middleware For Robots)
##
## (c) 1999, 2000, 2001, 2002, 2003
## Department of Neural Information Processing, University of Ulm, Germany
##
## $Id$
##
## Miro/src/video/Makefile.bin
##
##############################################################################

#----------------------------------------------------------------------------
#	Include macros
#----------------------------------------------------------------------------

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(MIRO_ROOT)/include/makeinclude/macros.miro.GNU

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

INSTALL = $(VBIN:%=$(INSBIN)/%)
MAKEFILE = Makefile.bin

## static libraries

STATIC_LIBS = miroVideo miroSvc

## performing the magic

STATIC_DEPS = $(addprefix $(MIRO_ROOT)/lib/lib, $(addsuffix .a,$(STATIC_LIBS)))
LDLIBS += $(addprefix -l, $(STATIC_LIBS))


## dynamic libraries if needed
ifneq (,$(findstring 1394,$(MIRO_VIDEO_COMPONENTS)))
  LDLIBS += -lraw1394 -ldc1394_control
endif
LDLIBS += -lmiro

## additional switches
ifneq (,$(findstring BTTV,$(MIRO_VIDEO_COMPONENTS)))
  CCFLAGS += -DMIRO_HAS_BTTV
endif

ifneq (,$(findstring Meteor,$(MIRO_VIDEO_COMPONENTS)))
  CCFLAGS += -DMIRO_HAS_Meteor
endif

ifneq (,$(findstring 1394,$(MIRO_VIDEO_COMPONENTS)))
  CCFLAGS += -DMIRO_HAS_1394
endif


## program to be built
## there has to exist a source file with the same name (mybinary.cc)
BIN 	= VideoService

## additional files
FILES = VideoService

SRC	= $(addsuffix .cpp,$(FILES))
OBJ	= $(addsuffix .o,$(FILES))

BUILD 	= $(VBIN)


#----------------------------------------------------------------------------
#	Include targets
#----------------------------------------------------------------------------

include $(TAO_ROOT)/rules.tao.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
include $(MIRO_ROOT)/include/makeinclude/rules.miro.GNU

#----------------------------------------------------------------------------
#	Local targets
#----------------------------------------------------------------------------

$(BIN): $(STATIC_DEPS)

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


.obj/VideoService.o .obj/VideoService.so .shobj/VideoService.o .shobj/VideoService.so: VideoService.cpp VideoServer.h VideoImpl.h \
 $(MIRO_ROOT)/src/miro/VideoS.h \
 $(MIRO_ROOT)/src/miro/ExceptionS.h \
 $(MIRO_ROOT)/src/miro/ExceptionC.h \
 $(MIRO_ROOT)/src/miro/ExceptionC.i \
 $(MIRO_ROOT)/src/miro/ExceptionS.i \
 $(MIRO_ROOT)/src/miro/TimeS.h \
 $(MIRO_ROOT)/src/miro/TimeC.h \
 $(MIRO_ROOT)/src/miro/TimeC.i \
 $(MIRO_ROOT)/src/miro/TimeS.i \
 $(MIRO_ROOT)/src/miro/PositionS.h \
 $(MIRO_ROOT)/src/miro/WorldPointS.h \
 $(MIRO_ROOT)/src/miro/WorldPointC.h \
 $(MIRO_ROOT)/src/miro/WorldPointC.i \
 $(MIRO_ROOT)/src/miro/WorldPointS.i \
 $(MIRO_ROOT)/src/miro/PositionC.h \
 $(MIRO_ROOT)/src/miro/PositionC.i \
 $(MIRO_ROOT)/src/miro/PositionS.i \
 $(MIRO_ROOT)/src/miro/VideoC.h \
 $(MIRO_ROOT)/src/miro/VideoC.i \
 $(MIRO_ROOT)/src/miro/VideoS.i \
 $(MIRO_ROOT)/src/miro/Synch.h \
 $(MIRO_ROOT)/src/miro/Server.h \
 $(MIRO_ROOT)/src/miro/Client.h \
 $(MIRO_ROOT)/src/miro/Exception.h \
 $(MIRO_ROOT)/src/miro/Parameters.h \
 $(MIRO_ROOT)/src/miro/ArbiterParameters.h \
 $(MIRO_ROOT)/src/miro/BehaviourParameters.h \
 $(MIRO_ROOT)/src/miro/Utils.h Parameters.h VideoDevice.h \
 VideoFilter.h VideoDeviceBTTV.h VideoAVDevice.h VideoDeviceMeteor.h \
 ioctl_meteor.h VideoDevice1394.h VideoDeviceDummy.h \
 VideoFilterRepository.h VideoFilterFactory.h VideoFilterBasic.h \
 VideoFilterYUV422toYUV.h VideoFilterYUV422toRGB.h \
 VideoFilterYUVbase.h VideoFilterYUV411toRGB.h \
 VideoFilterYUV411toYUV.h

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
