## -*- Makefile -*- ##########################################################
##
## This file is part of Miro (The Middleware For Robots)
##
## (c) 2003
## Department of Neural Information Processing, University of Ulm, Germany
##
## $Id$
##
## Miro/src/video/Makefile.lib
##
##############################################################################

#----------------------------------------------------------------------------
#	Include macros
#----------------------------------------------------------------------------

# Only build static library 
static_libs_only = 1

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(MIRO_ROOT)/include/makeinclude/macros.miro.GNU

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

## this is the name of the resulting library
NAME     = miroVideo

MAKEFILE = Makefile.lib
LIB      = lib$(NAME).a
SHLIB    = lib$(NAME).$(SOEXT)


## this I didn't understand yet
# VPATH=.:Naming
# ACE_SHLIBS = -lTAO_Svc_Utils -lTAO -lACE

## specify your library files here
FILES =  \
	Parameters \
	BufferManager \
	VideoFilter \
	VideoFilterBasic \
	VideoFilterRepository \
	VideoDevice \
	VideoAVDevice \
	VideoDeviceDummy \
	VideoConsumer \
	VideoImpl \
	VideoServer 

ifneq (,$(findstring BTTV,$(MIRO_VIDEO_COMPONENTS)))
  FILES += \
	VideoDeviceBTTV
endif

ifneq (,$(findstring Meteor,$(MIRO_VIDEO_COMPONENTS)))
  FILES += \
	VideoDeviceMeteor
endif

ifneq (,$(findstring 1394,$(MIRO_VIDEO_COMPONENTS)))
  FILES += \
	VideoDevice1394 \
	VideoFilterYUVbase \
	VideoFilterYUV411toRGB \
	VideoFilterYUV411toYUV \
	VideoFilterYUV422toRGB \
	VideoFilterYUV422toYUV
endif

DEFS  = $(addsuffix .h,$(FILES))
LSRC  = $(addsuffix .cpp,$(FILES))

#----------------------------------------------------------------------------
#	Include targets
#----------------------------------------------------------------------------

## you can toggle the debug and optimize flags at this point
# debug = 1
# optimize = 0

include $(TAO_ROOT)/rules.tao.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.lib.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
include $(MIRO_ROOT)/include/makeinclude/rules.miro.GNU

#----------------------------------------------------------------------------
#       Local targets (and local hacks)
#----------------------------------------------------------------------------

.PRECIOUS: Parameters.cpp Parameters.h

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


.obj/Parameters.o .obj/Parameters.o .obj/Parameters.o .obj/Parameters.o: Parameters.cpp Parameters.h \
 \
 \


.obj/BufferManager.o .obj/BufferManager.o .obj/BufferManager.o .obj/BufferManager.o: BufferManager.cpp BufferManager.h \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i

.obj/VideoFilter.o .obj/VideoFilter.o .obj/VideoFilter.o .obj/VideoFilter.o: VideoFilter.cpp VideoFilter.h Parameters.h \
 \
 \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/TimeC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i VideoImpl.h \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionS.i \
 /home/hutz/Miro/src/miro/TimeS.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointS.i \
 /home/hutz/Miro/src/miro/PositionS.i \
 /home/hutz/Miro/src/miro/VideoS.i BufferManager.h \
 \


.obj/VideoFilterBasic.o .obj/VideoFilterBasic.o .obj/VideoFilterBasic.o .obj/VideoFilterBasic.o: VideoFilterBasic.cpp VideoFilterBasic.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/TimeC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i \
 \
 \


.obj/VideoFilterRepository.o .obj/VideoFilterRepository.o .obj/VideoFilterRepository.o .obj/VideoFilterRepository.o: VideoFilterRepository.cpp \
 VideoFilterRepository.h VideoFilterFactory.h \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/TimeC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i \
 \
 VideoFilter.h Parameters.h \
 \
 \


.obj/VideoDevice.o .obj/VideoDevice.o .obj/VideoDevice.o .obj/VideoDevice.o: VideoDevice.cpp VideoDevice.h VideoFilter.h \
 Parameters.h \
 \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/TimeC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i \


.obj/VideoAVDevice.o .obj/VideoAVDevice.o .obj/VideoAVDevice.o .obj/VideoAVDevice.o: VideoAVDevice.cpp VideoAVDevice.h VideoDevice.h \
 VideoFilter.h Parameters.h \
 \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/TimeC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i \


.obj/VideoDeviceDummy.o .obj/VideoDeviceDummy.o .obj/VideoDeviceDummy.o .obj/VideoDeviceDummy.o: VideoDeviceDummy.cpp VideoDeviceDummy.h \
 VideoDevice.h VideoFilter.h Parameters.h \
 \
 \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/TimeC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i \
 \


.obj/VideoConsumer.o .obj/VideoConsumer.o .obj/VideoConsumer.o .obj/VideoConsumer.o: VideoConsumer.cpp VideoConsumer.h \
 \
 /home/hutz/Miro/src/miro/TimeC.i \
 VideoDevice.h VideoFilter.h Parameters.h \
 \
 \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/VideoC.i VideoImpl.h \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionS.i \
 /home/hutz/Miro/src/miro/TimeS.i \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointS.i \
 /home/hutz/Miro/src/miro/PositionS.i \
 /home/hutz/Miro/src/miro/VideoS.i \
 \


.obj/VideoImpl.o .obj/VideoImpl.o .obj/VideoImpl.o .obj/VideoImpl.o: VideoImpl.cpp VideoImpl.h \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/ExceptionS.i \
 \
 /home/hutz/Miro/src/miro/TimeC.i /home/hutz/Miro/src/miro/TimeS.i \
 \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/WorldPointS.i \
 \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/PositionS.i \
 /home/hutz/Miro/src/miro/VideoC.i \
 /home/hutz/Miro/src/miro/VideoS.i VideoDevice.h VideoFilter.h \
 Parameters.h \
 \
 VideoConsumer.h \
 BufferManager.h \
 \
 \
 \


.obj/VideoServer.o .obj/VideoServer.o .obj/VideoServer.o .obj/VideoServer.o: VideoServer.cpp VideoServer.h VideoImpl.h \
 \
 \
 \
 /home/hutz/Miro/src/miro/ExceptionC.i \
 /home/hutz/Miro/src/miro/ExceptionS.i \
 \
 /home/hutz/Miro/src/miro/TimeC.i /home/hutz/Miro/src/miro/TimeS.i \
 \
 \
 \
 /home/hutz/Miro/src/miro/WorldPointC.i \
 /home/hutz/Miro/src/miro/WorldPointS.i \
 \
 /home/hutz/Miro/src/miro/PositionC.i \
 /home/hutz/Miro/src/miro/PositionS.i \
 /home/hutz/Miro/src/miro/VideoC.i \
 /home/hutz/Miro/src/miro/VideoS.i VideoDevice.h VideoFilter.h \
 Parameters.h \
 \
 VideoConsumer.h \
 VideoFilterRepository.h \
 VideoFilterFactory.h \
 \


# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
