// -*- idl -*- ///////////////////////////////////////////////////////////////
//
// This file is part of Miro (The Middleware For Robots)
//
// for details copyright, usage and credits to other groups see Miro/COPYRIGHT
// for documentation see Miro/doc
// 
// (c) 1999,2000
// Department of Neural Information Processing, University of Ulm, Germany
//
// Authors: 
//    Stefan Enderle, 
//    Stefan Sablatnoeg, 
//    Hans Utz
// 
// $Id$
// 
//////////////////////////////////////////////////////////////////////////////
#ifndef SparrowPanTilt_idl
#define SparrowPanTilt_idl

#include "Pan.idl"

module Miro
{
  struct PanPositionIDL
  {
    double angle;
    double accuracy;
  };

  /**
   * Interface to a pan/ unit.
   */
  interface SparrowPanTilt : Pan
  {
    /** Is the pan unit still in motion? */
    boolean panning();

    /** Get pan position and accuracy */
    PanPositionIDL currentPan();
  };
};

#endif




